### ISSUE TITLE
Does not handle Running Status

### ISSUE THREAD

**Issue by AmeNote-Michael** [makbit/MIDI2USB#1]
System does not properly handle running status - used in many advanced controllers such as Roland, Yamaha, etc.

In MIDI 1.0 specification, see page 5 for more information. See Appendix A-4 for examples.

By not implementing Running Status, missed events do occur on controllers that implement it. For example, on Roland controller I am testing with, striking multiple keys at same time, only one key registered.

**Comment by AmeNote-Michael** [comment]
Does not properly handle Real-Time messages where only command/status byte and no data. These events are dropped. These are when command/status byte is masked with value 0xf8. Other than System Reset, messages are not managed and dropped.

Many advanced controllers use active sense (which is debatable if needed on USB, but if just implementing a DIN virtual cable, then may be needed, so just should support) and controller messages like play, stop, continue, etc. are common in many controllers - like DJ controllers.

I have implemented a simple fix where these messages create a new state known as MIDI_STATE_COMMAND_ONLY and then it completes a USB Packet with just command/status populated and all data zero filled, immediately returning to MIDI_STATE_IDLE when complete.

When I have time, I can implement into branch and push back (but will be unable to test on rest of your code as I do not have same processor setup).

**Comment by makbit** [comment]
Hello.
You are right. This firmware do not handle Real-time control and SysEx events. My keayboard does not support these messages. I cannot test it and I thought it was not important. Now I will change my mind.
I have found Table 4-2 in MIDI 1.0 spec with Examples of parsed events (page 17). It would be great if you show your 0xF8-command handler.

**Comment by AmeNote-Michael** [comment]
This looks promising for a method of providing test scenarios in absence of gear:
https://github.com/jazz-soft/test-midi-files

**Comment by makbit** [comment]
Sorry, I do not understand how to test USB device with MIDI files.

**Comment by AmeNote-Michael** [comment]
I am no longer actively using your library for a project, thus have not tested further. In my above suggestion, midi files have a set format - the list of files have a variety of known message formats. I would suggest you get / create a small device to use as your test where you parse the files and push in/out MIDI din to your hardware device, testing your device handling. There are a lot of example Raspberry Pi / Pico code out there to take the MiDI files and interact with DIN.
