### ISSUE TITLE
Does not properly handle Real-Time messages

### ISSUE THREAD

**Issue by AmeNote-Michael** [makbit/MIDI2USB#2]
Does not properly handle Real-Time messages where only command/status byte and no data. These events are dropped. These are when command/status byte is masked with value 0xf8. Other than System Reset, messages are not managed and dropped.

Many advanced controllers use active sense (which is debatable if needed on USB, but if just implementing a DIN virtual cable, then may be needed, so just should support) and controller messages like play, stop, continue, etc. are common in many controllers - like DJ controllers.

**Comment by makbit** [comment]
I think you are right. The code in [midi.c Line #80](https://github.com/makbit/MIDI2USB/blob/master/Firmware/midi.c) checks status byte and skips further processing.
` if( MIDI_IS_STATUS(dataRX) )            // System Real Time message`
I would appriciate for a patch. I do not have any DJ device, so I am not sure I can fix it fast.
I have found Table 4-2 in MIDI 1.0 spec with Examples of parsed events (page 17). It would be great if you show your 0xF8-command handler.

**Comment by AmeNote-Michael** [comment]
Here is some thoughts....

`			case MIDI_CLOCK:
			case MIDI_TICK:
			case MIDI_START:
			case MIDI_CONTINUE:
			case MIDI_STOP:
			case MIDI_ACTIVE_SENSE:
				state = MIDI_STATE_COMMAND_ONLY;
				break;`

`		else if ( state == MIDI_STATE_COMMAND_ONLY )
		{
			// Put MIDI message into the USB stream (zero padding).
			pUsbBuffer->pUSB_MIDI_Buffer[pUsbBuffer->nUSB_MIDI_Buffer_Count++] = 0x0f;		// cable 0, single byte message
			pUsbBuffer->pUSB_MIDI_Buffer[pUsbBuffer->nUSB_MIDI_Buffer_Count++] = dataRX;	// cmd
			pUsbBuffer->pUSB_MIDI_Buffer[pUsbBuffer->nUSB_MIDI_Buffer_Count++] = 0; 		// no data
			pUsbBuffer->pUSB_MIDI_Buffer[pUsbBuffer->nUSB_MIDI_Buffer_Count++] = 0;

			state == MIDI_STATE_IDLE;
		}`

Sorry, best I can do for now.

**Comment by makbit** [comment]
Thank you for your support. I have made changes and added Real-Time message handler. It would be great if you or someone else could test new release.

**Comment by AmeNote-Michael** [comment]
Sorry, no longer actively using library and unable to test / input further. Wish you luck.
